module.exports = {
  tents:[
    {
      name:"tent1",
      sku:"00001",
      manufacturer: "North Face",
      image: "https://prodimage.images-bn.com/pimages/9780262033848_p0_v1_s550x406.jpg",
      description:"Tent made for one person",
      size: "S",
      price: 40.00,
      qty: 5,
      rating: 3.5,
    },
    {
        name:"tent2",
        sku:"00002",
        manufacturer: "Field & Steam",
        image: "https://prodimage.images-bn.com/pimages/9780262033848_p0_v1_s550x406.jpg",
        description:"Spacious tent comfortable for two people",
        size: "L",
        price: 81.99,
        qty: 2,
        rating: 4.5,
    },
    {
        name:"tent3",
        sku:"00003",
        manufacturer: "Coleman",
        image: "https://prodimage.images-bn.com/pimages/9780262033848_p0_v1_s550x406.jpg",
        description:"Comfy tent that can fit a person with safety features",
        size: "M",
        price: 72.47,
        qty: 1,
        rating: 5.0,
    },
  ],
  shoes:[
    {
      name:"shoe1",
      sku:"00004",
      image: "https://i.imgur.com/O5anRKy.jpg",
      manufacturer:"Timberland",
      description:"lightweight and waterproof",
      price: 95.00,
      sizes: ["XS", "S", "M", "L", "XL"],
      qty: [12, 4, 1, 9, 3],
      rating: 3.5,
    },
    {
      name:"shoe2",
      sku:"00005",
      image: "https://i.imgur.com/m99ikTa.jpg",
      manufacturer:"Columbia",
      description:"Mesh with strong grip",
      price: 124.99,
      sizes: ["XS", "S", "M", "L", "XL"],
      qty: [7, 3, 1, 18, 0],
      rating: 4.5,
    },
    {
      name:"shoe3",
      sku:"00006",
      image: "https://www.dhresource.com/0x0/f2/albu/g9/M01/02/95/rBVaWFwR_nWAfkPFAAYIZWCWAhk407.jpg",
      manufacturer:"Merrell",
      description:"Ventilation focused boots",
      price: 85.99,
      sizes: ["XS", "S", "M", "L", "XL"],
      qty: [1, 3, 5, 2, 0],
      rating: 2.5,
    },
  ],
};