module.exports = {
  tents:[
    {
      name:"North Face Sequoia 2 Person Tent",
      sku:"00001",
      manufacturer: "North Face",
      image: "https://dks.scene7.com/is/image/GolfGalaxy/18TNOUSQ2XXXXXXXXCAT_Papaya_Yellow_High_Rise_Grey?qlt=70&wid=1100&fmt=webp",
      description:"Tent made for one person",
      size: "S",
      price: 40.00,
      qty: 5,
      rating: 3.5,
    },
    {
        name:"tent2",
        sku:"00002",
        manufacturer: "Field & Steam",
        image: "https://dks.scene7.com/is/image/GolfGalaxy/16FNSUFS7X6X463PRCAT_Orange?qlt=70&wid=1100&fmt=webp",
        description:"Spacious tent comfortable for two people",
        size: "L",
        price: 81.99,
        qty: 2,
        rating: 4.5,
    },
    {
        name:"tent3",
        sku:"00003",
        manufacturer: "Coleman",
        image: "https://dks.scene7.com/is/image/GolfGalaxy/19COLUHMPTN9PTNTXCAT?qlt=70&wid=1100&fmt=webp",
        description:"Comfy tent that can fit a person with safety features",
        size: "M",
        price: 72.47,
        qty: 1,
        rating: 5.0,
    },
  ],
  shoes:[
    {
      name:"shoe1",
      sku:"00004",
      image: "https://dks.scene7.com/is/image/GolfGalaxy/15TLDMMTMDDSNMDWPFBO_Brown?qlt=70&wid=1100&fmt=webp",
      manufacturer:"Timberland",
      description:"lightweight and waterproof",
      price: 95.00,
      sizes: ["XS", "S", "M", "L", "XL"],
      qty: [12, 4, 1, 9, 3],
      rating: 3.5,
    },
    {
      name:"shoe2",
      sku:"00005",
      image: "https://dks.scene7.com/is/image/GolfGalaxy/17CMBWNWTNRDGPLSMFBO_Black_Poppy_Red?qlt=70&wid=1100&fmt=webp",
      manufacturer:"Columbia",
      description:"Mesh with strong grip",
      price: 124.99,
      sizes: ["XS", "S", "M", "L", "XL"],
      qty: [7, 3, 1, 18, 0],
      rating: 4.5,
    },
    {
      name:"shoe3",
      sku:"00006",
      image: "https://dks.scene7.com/is/image/GolfGalaxy/17MRRWMB2VNTLMNMMFBO_Taupe?qlt=70&wid=1100&fmt=webp",
      manufacturer:"Merrell",
      description:"Ventilation focused boots",
      price: 85.99,
      sizes: ["XS", "S", "M", "L", "XL"],
      qty: [1, 3, 5, 2, 0],
      rating: 2.5,
    },
  ],
};